### ISSUE TITLE
Fix Scrutinizer path and add Codecov.io

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-dms#101]
Scrutinizer is still configured for silverstripe-labs/silverstripe-dms. Needs to be shifted by someone with admin access to the organisation.

Also, add Codecov.io integration via travis.yml

**Comment by tractorcow** [comment]
Your team is now admin on this module.

https://scrutinizer-ci.com/g/silverstripe/silverstripe-dms/inspections/a4ae458b-ba18-4109-b7b5-70600bd764b1

you need to setup codeconv https://codecov.io/gh/silverstripe/silverstripe-dms
