### ISSUE TITLE
'Link a Document' to a Document Set 'From the CMS' tab

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms#134]
When linking a document to a document set using the tab 'From the CMS', the SilverStripe logo continuously spins and the 'edit' button is also unable to be selected.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
