### ISSUE TITLE
Fix permissions for adding docs to doc sets (currently only admins)

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-dms#135]

**Comment by robbieaverill** [comment]
The model admin in this module already adds "Access to 'Documents' section" as a provided permission, and you can adjust on a per-document level as well. Do we need to add more fine-grained permissions for this?

**Comment by robbieaverill** [comment]
We'll add some new ones.

**Comment by robbieaverill** [comment]
Requires some refactoring across the module as permissions have not been implemented throughout in the past.

**Comment by robbieaverill** [comment]
#168 goes a way towards "fixing" this, but it still needs some more love at some stage.

**Comment by fspringveldt** [comment]
Fixed by #168
