### ISSUE TITLE
Please rename JsonField to DMSJsonField as conflict with other modules

### ISSUE THREAD

**Issue by wakes** [silverstripe/silverstripe-dms#139]
https://github.com/silverstripe/silverstripe-dms/commit/6b25237ec6c85f556dd1d6aac29772a3d6288ce2

...added a field called 'JsonField' which conflicts with e.g. document-vault module being used at mpi (and probably a few other modules and applications out there). Could it be 'namespaced' by renaming it to DMSJsonField or some such please?

**Comment by robbieaverill** [comment]
Good idea @wakes - fix at #140
