### ISSUE TITLE
Make DMS work with static publisher

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-dms#15]
Currently files included via the DMS can't be access via staticpublisher.  This is a problem if you're using staticpublisher for security rather than performance reasons, and your public server has no access to static files.

The following changes would be needed:
- Amend the link generation so that dms links have the filename at the end. "dmsdocument/3" becomes "dmsdocument/3/myfile.pdf".  It will be ignored by the controller, but it makes the links friendlier.
- Add links such as "dmsdocument/3/myfile.pdf" to the set of static publisher URLs in the static publisher configuration.  StaticPublihser Core would need to allow for SiteTree extensions to specify cacheable URLs, and the DMS sitetree extension would need to implement this.
- Have staticpublisher add ".html" to the end of the destination filename only when there isn't an existing extension.  This is a core change.
- Have the staticpublisher rewriterule look for a file without a ".html" extension if one with a ".html" extension doesn't exist.  This would be an .htaccess change, made in the staticpublisher set-up instructions
- Hook a republish in onafterwrite of DMSDocument, to make sure replacing a document updates the appropriate statically published file.
- The embargo/expiry feature of DMS introduces a bunch of other issues. Maybe embargo/expiry only works on a day granularity when a full republish happens? Or perhaps disable the embargo/expiry feature altogether (I think there is a static variable somewhere to set that).

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
