### ISSUE TITLE
Wrong display message when pressing 'done'

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms#156]
Wrong display message when uploading documents to a set and pressing ‘Done!’ (there probably shouldn’t be any message at all).

Pre-existing bug in the DMS module possibly comes from framework.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
