### ISSUE TITLE
"Show allowed extensions" link should be hidden by default

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms#178]
When uploading documents from the "Documents" model admin or in pages the "Show allowed extensions" link should be hidden by default.

![show_allowed_extensions](https://user-images.githubusercontent.com/24258161/27162296-96b892c8-51d4-11e7-83e5-2891d98fcd17.png)

The "Show allowed extensions" link should behave the same as it does when uploading from the "Files" section.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
