### ISSUE TITLE
Inconsistent permission checks in DMSDocument.canEdit

### ISSUE THREAD

**Issue by wakes** [silverstripe/silverstripe-dms#183]
Hi guys, 

DMSDocument.canEdit method checks permissions of current member twice, first time for ADMIN, SITETREE_EDIT_ALL, SITETREE_VIEW_ALL, second time just ADMIN, SITETREE_EDIT_ALL. It should probably not consider SITETREE_VIEW_ALL to be a 'can edit' permission in the first check?

DMS version dev-master (2.0.x-dev) https://github.com/silverstripe/silverstripe-dms/blob/master/code/model/DMSDocument.php#L158

Cheers,
Steve

**Comment by robbieaverill** [comment]
Hey @wakes - thanks for reporting this. We plan to overhaul the way permissions are handled at some stage, but this is a bit of a stop gap solution for 2.0 to ensure that there is some level of control. The issue we'll follow up on is #135, and will cover things like this in that issue.

**Comment by wakes** [comment]
Ok cool, thanks for quick response.

**Comment by robbieaverill** [comment]
Re-checked, #135 is actually resolved now. We should consider this issue on its own merit.

**Comment by wakes** [comment]
@robbieaverill cool, any eta? Looks like lots of stuff happening at the moment on DMS so maybe soonish?

**Comment by robbieaverill** [comment]
@wakes it'll be fixed up before 2.0.0 stable

**Comment by sachajudd** [comment]
Fixed in #184 and released in 2.0.1 @wakes, thanks for reporting 🙂
