### ISSUE TITLE
Composer installation of silverstripe-dms fails in SS4

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-dms#185]
After a fresh install of SS4, none of the following worked:
`composer require silverstripe/dms`
`composer require silverstripe/dms dev-master`
`composer require silverstripe/dms 2.0.1`. 

Here is the composer output in the case of trying to install with dev-master:

![screenshot from 2017-07-05 16-29-58](https://user-images.githubusercontent.com/8912185/27849185-40e471c0-619f-11e7-940f-6f5dcb07ca14.png)

**Comment by robbieaverill** [comment]
Hey @SpiritLevel - DMS is not SilverStripe compatible, and we don't have plans to upgrade the module since SS4 supports most of the features of this module out of the box; secure assets, versioned assets, etc.

**Comment by SpiritLevel** [comment]
Doh...I must have missed that key point when reading the docs! Sorry :)

**Comment by robbieaverill** [comment]
No worries :-) it's probably not in the DMS docs
