### ISSUE TITLE
dms documents get synced into assets table

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-dms#190]
the DMS documents show up in the assets table after a file system sync. even though the general underscore folder doesn't show in the CMS, the files still get synced into the table because the sync exclusion on https://github.com/silverstripe/silverstripe-framework/blob/3.6/filesystem/Filesystem.php#L35-L41 doesn't exclude all underscore folders.

**Comment by robbieaverill** [comment]
Nice spotting @xini. Would you like to PR a fix? Probably just merge in the configured DMS folder name into that config static via `_config.php`, or something similar.

**Comment by xini** [comment]
which branch do you want the fix on? 
Also, would a `FileSystem.sync_blacklisted_patterns` in either config.yml or _config.php be merged into the existing array? Or would I need to 'manually' merge the new value into the array?

**Comment by robbieaverill** [comment]
I think this could go into the `2.0` branch @xini as a patch semver fix. 

>Also, would a FileSystem.sync_blacklisted_patterns in either config.yml or _config.php be merged into the existing array? Or would I need to 'manually' merge the new value into the array?

Yes, it would be merged.

You'll need to do this in `_config.php` because the folder name is configurable as well, so YAML would be to early to achieve this without duplicating the folder name value.
