### ISSUE TITLE
insert link to document in htmleditorfield

### ISSUE THREAD

**Issue by georgecaompi** [silverstripe/silverstripe-dms#192]
The backend admin can’t insert a link to a document in content htmleditorfield.

1. ShortcodeHandlerKey Field is missing in DocumentHtmlEditorFieldToolbar.php
2. invalid RegExp expression inside getCurrentLink block  in DocumentHtmlEditorFieldToolbar.js   

thanks

George

**Comment by robbieaverill** [comment]
Fixed with #194 and available in 2.0.4. Noted UX issues still persist - see comment in #194
