### ISSUE TITLE
Ability to disable DocumentSets intermediary structure

### ISSUE THREAD

**Issue by jaedb** [silverstripe/silverstripe-dms#197]
For any small- to medium-sized website (or any website with less than hundreds of documents), _Document Sets_ pose a superfluous level of structure that users find both frustrating and confusing. We find ourselves struggling to justify their purpose to our clients.

That being said, large-scale website with hundreds of documents (eg Government-level websites) suit the _Document Sets_ structure really well.

To this end, I propose that developers (or better yet, administrators) can opt-in to the _Document Sets_ structure. This could be the ability for documents to be attached directly to pages (as was previously the case), or perhaps a configuration value to disable _Document Sets_ completely.

**Comment by robbieaverill** [comment]
Hi @jaedb - it makes sense to me that you could make this configurable. There's a couple of ways that this could be done:

* Dev configuration setting
* SiteConfig global setting
* Page/DataObject specific setting (could allow you to turn document sets on or off for a specific page but not all)
* A combination of all the above

I think the easiest way to implement this kind of feature would be that if you don't want document sets the backend would still create one by default, but have it hidden from CMS users and the templates. This way we wouldn't have to change the data model architecture, but rather just add some config settings and some logic in an onBeforeWrite hook somewhere.

Would you be keen to submit a pull request for this?

**Comment by jaedb** [comment]
That sounds like a reasonable approach. No point interfering with the data model architecture if we can avoid it - provided it doesn't start introducing clunky logic.

I'm happy to explore the implementation of this.

**Comment by camfindlay** [comment]
+1

**Comment by camfindlay** [comment]
I flag in the config.yml would be ideal

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
