### ISSUE TITLE
Deprecated getDocumentSets() method called in CMS 

### ISSUE THREAD

**Issue by AndrewHaine** [silverstripe/silverstripe-dms#208]
DMS Version 2.2.0

When visiting a page with document sets in the CMS the deprecation notice is shown - looks like this is a result of the way ViewableData automatically prepends 'get' when retrieving properties:
```php
// ViewableData.php line 119
if (strtolower($property) !== 'field' && $this->hasMethod($method = "get$property"))
```

**Comment by NightJar** [comment]
Thanks for reporting @AndrewHaine 
In order for a deprecation notice to be displayed, your site must be [configured](https://docs.silverstripe.org/en/3/getting_started/environment_management/#setting-up-your-development-machine-with-ss-environment-php) into `dev` mode, which is generally unadvisable for production sites.

The method was deprecated recently (in https://github.com/silverstripe/silverstripe-dms/pull/206) to fix a 500 error related to the magic lookup you're referring to in ViewableData (infinite recursion).

If you'd like to disable deprecation notices in your development environment you can choose to either:
- for this project: `Deprecation::set_enabled(false);` (e.g. in `mysite/_config.php`)
- for all projects: `define('SS_DEPRECATION_ENABLED', false);` in your `_ss_environment.php` file.

You can see from the calltime check at https://github.com/silverstripe/silverstripe-framework/blob/3.6/dev/Deprecation.php#L138
