### ISSUE TITLE
Deprecation Notice in SS3.6.6

### ISSUE THREAD

**Issue by mspacemedia** [silverstripe/silverstripe-dms#213]
I'm sure you all know, but the current version produces this error when viewing a page in the sitetree under 3.6.6 under dev conditions.

`[User Deprecated] DMSSiteTreeExtension->getDocumentSets is deprecated. Use DocumentSets() instead. Called from call_user_func_array.`

```Deprecation::notice(3.0,Use DocumentSets() instead) 
DMSSiteTreeExtension.php:64
DMSSiteTreeExtension->getDocumentSets() 
call_user_func_array(Array,Array) 
Object.php:749
Object->__call(getDocumentSets,Array) 
ViewableData.php:120
Page->getDocumentSets() 
ViewableData.php:120
ViewableData->__get(DocumentSets) 
Form.php:1433```

**Comment by robbieaverill** [comment]
Deprecating APIs is fine, but if we are still using them then we need to fix it

**Comment by mspacemedia** [comment]
Well, that's true but it gets called by the framework in 3.6.6 here: ViewableData->__get(DocumentSets) 

Not quite sure how one would go about fixing this issue to be honest.

**Comment by dhensby** [comment]
That's not really where it gets called. it's either called like this: `$obj->DocumentSets` or in a template as `$DocumentSets`. Do you have the full stacktrace?

**Comment by NightJar** [comment]
Error:
>Don't use `getDocumentSets`
>Do use `DocumentSets`

Stacktrace: _does_ reference DocumentSets (sans 'get' prefix)
`ViewableData->__get(DocumentSets)`

Problem: `get{$thatThing}` is the first check to call
https://github.com/silverstripe/silverstripe-framework/blob/3.6.6/view/ViewableData.php#L119

Relevant: deprecation added as resolution of 500 server error.
https://github.com/silverstripe/silverstripe-dms/pull/206#discussion_r179969551

**Comment by robbieaverill** [comment]
To be honest, this was a mistake on our part in using the getter originally, then being asked to stop using so deprecating it for the sake of not breaking semantic versioning by removing it completely. I guess we need to just remove it altogether and break it for sake of it.

**Comment by ScopeyNZ** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
