### ISSUE TITLE
DMSEmbargoTest::testExpireAtDate is broken

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-dms#221]
DMSEmbargoTest::testExpireAtDate is broken.

```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
....................................FF.............S............. 65 / 88 ( 73%)
.......................                                           88 / 88 (100%)
Time: 1.8 minutes, Memory: 118.00MB
There were 2 failures:
1) DMSEmbargoTest::testExpireAtDate
Document is not hidden
Failed asserting that true is false.
/home/travis/build/ss/dms/tests/DMSEmbargoTest.php:78
/home/travis/build/ss/vendor/phpunit/phpunit/phpunit:52
2) DMSEmbargoTest::testEmbargoUntilDate
Document is hidden
Failed asserting that false is true.
/home/travis/build/ss/dms/tests/DMSEmbargoTest.php:119
/home/travis/build/ss/vendor/phpunit/phpunit/phpunit:52
```

 - 2.2 : https://travis-ci.org/silverstripe/silverstripe-dms/jobs/617393209
 - 2.1 :  https://travis-ci.org/silverstripe/silverstripe-dms/jobs/418435298

This appears to be a regression in the module dependencies since it is now broken in 2.1 test which was green 1 year ago (I just reran it today).

**Comment by emteknetnz** [comment]
PRs:
master: https://github.com/silverstripe/silverstripe-dms/pull/223
2.2: https://github.com/silverstripe/silverstripe-dms/pull/224
2.1: https://github.com/silverstripe/silverstripe-dms/pull/225

**Comment by maxime-rainville** [comment]
Looks like all the builds are green now https://travis-ci.org/silverstripe/silverstripe-dms/branches

Epic effort @emteknetnz !
