### ISSUE TITLE
Allow default browser treatment of PDFs?

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-dms#41]
Is there any way to allow the default browser behaviour treatment for PDFs eg. Viewing within the browser if that's what the user normally encounters/prefers?

I think if the user is expecting to quick view a PDF in the browser as they normally would, then the automatic download is a bit annoying.

**Comment by jaedb** [comment]
@neilcreagh 100% agree. We've been working on this very issue. Watch this space for a pull request...

**Comment by robbieaverill** [comment]
Fixed in #90. Looks like an issue came out regarding configuration, however this should be logged separately.
