### ISSUE TITLE
Can't select documents from draft cms pages

### ISSUE THREAD

**Issue by svandragt** [silverstripe/silverstripe-dms#45]
From http://doc.silverstripe.org/framework/en/3.1/changelogs/3.1.2

> In order to provide more secure default behaviour, we have changed choose_site_stage() to be called on all requests, defaulting to the "Live" stage. If your logic relies on querying draft content, use Versioned::reading_stage('Stage').

If you create a draft page and add documents to them, you cannot select them from another page.

Is this on purpose so that draft documents aren't leaked (documents belonging to draft pages are draft documents) or is this an issue resulting from 3.1.2 changes because DRM used to show draft documents in the past?

**Comment by robbieaverill** [comment]
Hi @svandragt - this is a pretty old issue now. I've just tested this on 3.5.3 and it looks resolved. If you are still having problems, feel free to reopen. Thanks!
