### ISSUE TITLE
Out of Memory Errors

### ISSUE THREAD

**Issue by christopher-s** [silverstripe/silverstripe-dms#78]
When a user attempts to download a file from the DMS that is larger than PHP's memory limit, the download will fail.

The solution is to change "flush();" from this line:
https://github.com/silverstripe-labs/silverstripe-dms/blob/master/code/model/DMSDocument.php#L1356

To "ob_end_flush()".

**Comment by dhensby** [comment]
I assume that's because the file won't be buffered in memory and then sent later?

What if there are nested output buffers, will this still work?

**Comment by christopher-s** [comment]
I think there must be nested output buffers, otherwise the single "flush()" would have solved it.
So, using ob_end_flush() closes all output buffers and sends with readfile().

According to readfile() documentation (http://php.net/manual/en/function.readfile.php):

> readfile() will not present any memory issues, even when sending large files, on its own. If you encounter an out of memory error ensure that output buffering is off with ob_get_level().

**Comment by dhensby** [comment]
looks like you'd have to use a while (http://php.net/manual/en/function.ob-end-flush.php#refsect1-function.ob-end-flush-examples)

**Comment by robbieaverill** [comment]
Hi @christopher-s - would you be keen to submit a pull request for this?

**Comment by christopher-s** [comment]
@robbieaverill Yeah, I can try to do that this weekend.

**Comment by robbieaverill** [comment]
Updated link showing the code in question: https://github.com/silverstripe/silverstripe-dms/blob/1.4.0/code/model/DMSDocument.php#L1412

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
